### ISSUE TITLE
Disable twigx for some lines

### ISSUE THREAD

**Issue by mhlozek** [lmc-eu/twigx-bundle#24]
We have file with some custom _tags_, which are not part of twigx components.

Could you add something like linting comments?, 

E.g.: 

```
{# twigx-disable #}

...this should not be parsed...

{# twigx-enable #}
```

**Comment by literat** [comment]
@mhlozek Hi, could you provide please, a more descriptive example of your custom tags or an entire example of the file you would like to parse?

I am not certain about this request because the main goal of TwigX is to provide JSX-like syntax in Twig templates. You still use the default Twig syntax while using TwigX but when you want to combine it with other custom JSX-like syntax it could lead to a mismatch or lower the readability of your code.

I think it is possible to achieve this by modifying the regular expression in https://github.com/lmc-eu/twigx-bundle/blob/main/src/Compiler/ComponentTagCompiler.php.
The Twig comments within the body of the TwigX tag are supported (https://github.com/lmc-eu/twigx-bundle/blob/main/src/Compiler/ComponentTagCompiler.php#LL115C28-L115C28) so you can inspire yourself here and prepare a PR for this. :-)

But still, I am not sure about this and I would like to read some more information and arguments about this issue.

Thank you for your interest :-)

**Comment by mhlozek** [comment]
We are moving from TwigX to [Symfony UX Twig components](https://symfony.com/bundles/ux-twig-component/current/index.html). 

Goodbye and thanks for everything :)

**Comment by literat** [comment]
@mhlozek Good choice! They are doing a great job. We were also considering adopting them but it looks like that we will be moving another way. :-)

Also, Symfony Live components are worth exploring - https://symfony.com/bundles/ux-live-component/current/index.html ;-)
